name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do respositorio
      uses: actions/checkout@v4.1.1
    - name: Efeturar o login no docker hub
      run: echo "Executar o docker login"
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    - name: Construir a imagem de container
      run: echo "Executar o docker build"
    - name: Enviar a imagem para o docker registry
      run: echo "Executar o docker push"
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./kube-news/src
        file: ./kube-news/src/Dockerfile
        push: true
        tags:
          danveras/kubenews:${{ github.run_number }}
          danveras/kubenews:latest
          
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Autenticar na AWS
      run: echo "Autenticar na AWS"
    - name: Configurar o KubeConfig
      run: echo "Configurar o KubeConfig"
    - name: Aplicar o Deploy
      run: echo "Executar o kubectl apply"
      
