name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.1
    - name: Efeturar o login no docker hub
      run: echo "Executar o docker login"
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    - name: Construir a imagem de container
      run: echo "Executar o docker build"
    - name: Enviar a imagem para o docker registry
      run: echo "Executar o docker push"
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./kube-news/src
        file: ./kube-news/src/Dockerfile
        push: true
        tags: |
          danveras/kubenews:${{ github.run_number }}
          danveras/kubenews:latest
          
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4.1.1
    - name: Autenticar na AWS
      run: echo "Autenticar na AWS"
    - name: Configuração da credencial da AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: east-us-1
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }} 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    - name: Configurar o KubeConfig
      run: echo "Configurar o KubeConfig"
      run: aws eks update-kubeconfig --name imersao-eks --region us-east-1
    - name: Aplicar o Deploy
      run: echo "Executar o kubectl apply"
    - name: Deploy to Kubernetes cluster
    uses: Azure/k8s-deploy@v4.9
    with:
      manifest: |
        ./kube-news/k8s/deployment.yaml
      images: |
        danveras/kubenews:${{ github.run_number }}
      
